public class Main {
    public static void main(String[] args) {
        byte apple = 111;
        short samsung = 11111;
        int xiaomi = 1111111111;
        long honor = 1111111111111111L;
        float milk = 1.1111f;
        double coffee = 1.111111111111;
        System.out.println(apple);
        System.out.println(samsung);
        System.out.println(xiaomi);
        System.out.println(honor);
        System.out.println(milk);
        System.out.println(coffee);
        double theWeightOfTheFirstBoxer = 78.2;
        double WeightOfTheSecondBoxer = 82.7;
        double totalWeight = WeightOfTheSecondBoxer + theWeightOfTheFirstBoxer;
        double weightDifference = WeightOfTheSecondBoxer - theWeightOfTheFirstBoxer;
        System.out.println("вес первого боксера " + theWeightOfTheFirstBoxer + " кг");
        System.out.println("вес второго боксера " + WeightOfTheSecondBoxer + " кг");
        System.out.println("общий вес боксеров " + totalWeight + " кг");
        System.out.println("разница в весе боксеров " + weightDifference + " кг");
        double banana = 80;
        double milk100ml = 105;
        double iceСreamSundae = 100;
        double egg = 70;
        double breakfastWeightG = banana * 5 + milk100ml * 2 + iceСreamSundae  * 2+ egg * 4;
        double breakfastWeightKg = breakfastWeightG / 1000;
        System.out.println("общий вес завтрака " + breakfastWeightG + " г");
        System.out.println("общий вес завтрака " + breakfastWeightKg + " кг");
        double theGoalIsToLoseWeight = 7;
        double weightLossPerDayG250 = 250;
        double weightLossPerDayKg250 = weightLossPerDayG250 / 1000;
        double ItWillTakeDays250 = theGoalIsToLoseWeight / weightLossPerDayKg250;
        System.out.println("потребуется для похудения " + ItWillTakeDays250 + " дней");
        double weightLossPerDayG500 = 500;
        double weightLossPerDayKg500 = weightLossPerDayG500 / 1000;
        double ItWillTakeDays500 = theGoalIsToLoseWeight / weightLossPerDayKg500;
        System.out.println("потребуется для похудения " + ItWillTakeDays500 + " дней");
        double sumOfDays = ItWillTakeDays250 + ItWillTakeDays500;
        double averageNumberOfDays = sumOfDays / 2;
        System.out.println("в среднем потребуется для похудения " + averageNumberOfDays + " день");
        var MashaHasSalary = 67760;
        var DenisHasSalary = 83690;
        var KristinaHasSalary = 76230;
        var MashaHasSalaryPerYear = MashaHasSalary * 12;
        var DenisHasSalaryPerYear = DenisHasSalary * 12;
        var KristinaHasSalaryPerYear = KristinaHasSalary * 12;
        var MashaHasSalaryAfterThePromotion = MashaHasSalary * 1.1;
        var DenisHasSalaryAfterThePromotion = DenisHasSalary * 1.1F;
        System.out.println(DenisHasSalaryAfterThePromotion);
        var KristinaHasSalaryAfterThePromotion = KristinaHasSalary * 1.1;
        var MashaHasSalaryAfterThePromotionPerYear = MashaHasSalaryAfterThePromotion * 12;
        var DenisHasSalaryAfterThePromotionPerYear = DenisHasSalaryAfterThePromotion * 12;
        var KristinaHasSalaryAfterThePromotionPerYear = KristinaHasSalaryAfterThePromotion * 12;
        var increaseInMashaHasAnnualIncome = MashaHasSalaryAfterThePromotionPerYear - MashaHasSalaryPerYear;
        var increaseInDenisHasAnnualIncome = DenisHasSalaryAfterThePromotionPerYear - DenisHasSalaryPerYear;
        var increaseInKristinaHasAnnualIncome = KristinaHasSalaryAfterThePromotionPerYear - KristinaHasSalaryPerYear;
        System.out.println("Маша теперь получает " + MashaHasSalaryAfterThePromotion + " рублей. Годовой доход вырос на " + increaseInMashaHasAnnualIncome + " рублей.");
        System.out.println("Денис теперь получает " + DenisHasSalaryAfterThePromotion + " рублей. Годовой доход вырос на " + increaseInDenisHasAnnualIncome + " рублей.");
        System.out.println("Кристина теперь получает " + KristinaHasSalaryAfterThePromotion + " рублей. Годовой доход вырос на " + increaseInKristinaHasAnnualIncome + " рублей.");
    }
}
